# This scenario generates infinite batches of 100 sets of 100 metrics of up to
# 1000 in value. Notice the batch: 0 argument passed to the hammer module, this
# means infinite batches, and thus, it will run until killed with Ctrl-C

# The metrics will be sent in graphite plaintext format to graphite-0001:2003.
# Any metrics which fail to be sent will be retried after 1 second. If the
# commented lines in this scenario are uncommented, these failed packets will
# be printed to stdout and dropped instead.
---
modules:

  hammer:
    module: metricfactory.test.hammer
    arguments:
      batch: 0
      batch_size: 100
      set_size: 100
      value: 1000
      sleep: 0

  encodegraphite:
    module: wishbone.builtin.metrics.graphite

  tcp:
    module: wishbone.output.tcp
    arguments:
      host: graphite-0001
      port: 2003
      # failed: True

  # stdout:
    # module: wishbone.builtin.output.stdout

routingtable:
  - hammer.outbox             -> encodegraphite.inbox
  - encodegraphite.outbox     -> tcp.inbox
  # - tcp.failed                -> stdout.inbox
...
