# This scenario generates a single batch of 100 sets of 100 metrics with a
# maximum value of 1000 and sends them to localhost:2003 in graphite's plain
# text format

# the metrics will be named
# hammer.metricfactory.hammer.set_<1 to 100>.metric_<1 to 100>
---
modules:

  hammer:
    module: metricfactory.test.hammer
    arguments:
      batch: 1
      batch_size: 100
      set_size: 100
      value: 1000

  encodegraphite:
    module: wishbone.builtin.metrics.graphite

  tcp:
    module: wishbone.output.tcp
    arguments:
      host: graphite-0001
      host: localhost
      port: 2003
      failed: True

routingtable:

  - hammer.outbox             -> encodegraphite.inbox
  - encodegraphite.outbox     -> tcp.inbox
...
